language: android
jdk:
    - oraclejdk7
    - oraclejdk8
android:
  components:
    - build-tools-23.0.2
    - android-23
    - extra-android-support
    - extra-android-m2repository
  licenses:
    - '.+'

before_install:
    - export JAVA7_HOME=/usr/lib/jvm/java-7-oracle
    - export JAVA8_HOME=/usr/lib/jvm/java-8-oracle
    - export JAVA_HOME=$JAVA8_HOME
    - echo yes | android update sdk --all --filter build-tools-23.0.2 --no-ui --force > /dev/null
script:
    - ./gradlew clean assemble check
